# Bundle static assets with nginx
FROM nginx:stable-alpine as production
ENV NODE_ENV production
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copy build from host
COPY dist /usr/share/nginx/html
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]